# Generated by Django 3.2.9 on 2021-12-04 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("guest_user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomGuest",
            fields=[
                (
                    "guest_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="guest_user.guest",
                    ),
                ),
                (
                    "extra_data",
                    models.CharField(blank=True, default="dummy", max_length=255),
                ),
            ],
            bases=("guest_user.guest",),
        ),
    ]
