# Generated by Django 3.2.18 on 2023-03-07 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Guest', 'verbose_name_plural': 'Guests'},
        ),
    ]
